name: create_artifact

on: [push]

env: 
  ARTIFACT_NAME: myArtifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}    
          path: .
  

